// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import ScrollDownWhenNewMessageController from "./scroll_down_when_new_message_controller"
application.register("scroll-down-when-new-message", ScrollDownWhenNewMessageController)

import UpdateImageOnLoadFinishController from "./update_image_on_load_finish_controller"
application.register("update-image-on-load-finish", UpdateImageOnLoadFinishController)
